#Seleccionamos al imagen python de dockerHub
FROM python3.12.10slim
#Nombramos la carpeta de trabajo
WORKDIR /Backend
#Copiamos el archivo requirements a la carpeta de trabajo
COPY ./requirements.txt .
#ejecutamos el comando para instalar dependencias en el contenedor
RUN 'pip install -r requirements.txt'
#Copiamos todo el contenido del proyecto al contenedor(Evaidendo contenido DockerIgnore)
COPY . .
#Expomemos el puerto 5000 del contenedor
EXPOSE 5000
#Ejecutamos una sentencia CMD (Runner)
CMD [ "" ]